import type { ThemePreset } from "@/types/theme";

export const defaultPresets: Record<string, ThemePreset> = {
  "modern-minimal": {
    label: "Modern Minimal",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#333333",
        card: "#ffffff",
        "card-foreground": "#333333",
        popover: "#ffffff",
        "popover-foreground": "#333333",
        primary: "#3b82f6",
        "primary-foreground": "#ffffff",
        secondary: "#f3f4f6",
        "secondary-foreground": "#4b5563",
        muted: "#f9fafb",
        "muted-foreground": "#6b7280",
        accent: "#e0f2fe",
        "accent-foreground": "#1e3a8a",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#e5e7eb",
        input: "#e5e7eb",
        ring: "#3b82f6",
        "chart-1": "#3b82f6",
        "chart-2": "#2563eb",
        "chart-3": "#1d4ed8",
        "chart-4": "#1e40af",
        "chart-5": "#1e3a8a",
        radius: "0.375rem",
        sidebar: "#f9fafb",
        "sidebar-foreground": "#333333",
        "sidebar-primary": "#3b82f6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e0f2fe",
        "sidebar-accent-foreground": "#1e3a8a",
        "sidebar-border": "#e5e7eb",
        "sidebar-ring": "#3b82f6",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Source Serif 4, serif",
        "font-mono": "JetBrains Mono, monospace",
      },
      dark: {
        background: "#171717",
        foreground: "#e5e5e5",
        card: "#262626",
        "card-foreground": "#e5e5e5",
        popover: "#262626",
        "popover-foreground": "#e5e5e5",
        primary: "#3b82f6",
        "primary-foreground": "#ffffff",
        secondary: "#262626",
        "secondary-foreground": "#e5e5e5",
        muted: "#1f1f1f",
        "muted-foreground": "#a3a3a3",
        accent: "#1e3a8a",
        "accent-foreground": "#bfdbfe",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#404040",
        input: "#404040",
        ring: "#3b82f6",
        "chart-1": "#60a5fa",
        "chart-2": "#3b82f6",
        "chart-3": "#2563eb",
        "chart-4": "#1d4ed8",
        "chart-5": "#1e40af",
        radius: "0.375rem",
        sidebar: "#171717",
        "sidebar-foreground": "#e5e5e5",
        "sidebar-primary": "#3b82f6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#1e3a8a",
        "sidebar-accent-foreground": "#bfdbfe",
        "sidebar-border": "#404040",
        "sidebar-ring": "#3b82f6",
      },
    },
  },
  "violet-bloom": {
    label: "Violet Bloom",
    createdAt: "2025-06-26",
    styles: {
      light: {
        background: "#fdfdfd",
        foreground: "#000000",
        card: "#fdfdfd",
        "card-foreground": "#000000",
        popover: "#fcfcfc",
        "popover-foreground": "#000000",
        primary: "#7033ff",
        "primary-foreground": "#ffffff",
        secondary: "#edf0f4",
        "secondary-foreground": "#080808",
        muted: "#f5f5f5",
        "muted-foreground": "#525252",
        accent: "#e2ebff",
        "accent-foreground": "#1e69dc",
        destructive: "#e54b4f",
        "destructive-foreground": "#ffffff",
        border: "#e7e7ee",
        input: "#ebebeb",
        ring: "#000000",
        "chart-1": "#4ac885",
        "chart-2": "#7033ff",
        "chart-3": "#fd822b",
        "chart-4": "#3276e4",
        "chart-5": "#747474",
        sidebar: "#f5f8fb",
        "sidebar-foreground": "#000000",
        "sidebar-primary": "#000000",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#ebebeb",
        "sidebar-accent-foreground": "#000000",
        "sidebar-border": "#ebebeb",
        "sidebar-ring": "#000000",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.16",
        "shadow-blur": "3px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },
      dark: {
        background: "#1a1b1e",
        foreground: "#f0f0f0",
        card: "#222327",
        "card-foreground": "#f0f0f0",
        popover: "#222327",
        "popover-foreground": "#f0f0f0",
        primary: "#8c5cff",
        "primary-foreground": "#ffffff",
        secondary: "#2a2c33",
        "secondary-foreground": "#f0f0f0",
        muted: "#2a2c33",
        "muted-foreground": "#a0a0a0",
        accent: "#1e293b",
        "accent-foreground": "#79c0ff",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#33353a",
        input: "#33353a",
        ring: "#8c5cff",
        "chart-1": "#4ade80",
        "chart-2": "#8c5cff",
        "chart-3": "#fca5a5",
        "chart-4": "#5993f4",
        "chart-5": "#a0a0a0",
        sidebar: "#161618",
        "sidebar-foreground": "#f0f0f0",
        "sidebar-primary": "#8c5cff",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#2a2c33",
        "sidebar-accent-foreground": "#8c5cff",
        "sidebar-border": "#33353a",
        "sidebar-ring": "#8c5cff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.16",
        "shadow-blur": "3px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },
    },
  },

  "t3-chat": {
    label: "T3 Chat",
    createdAt: "2025-04-19",
    styles: {
      light: {
        background: "#faf5fa",
        foreground: "#501854",
        card: "#faf5fa",
        "card-foreground": "#501854",
        popover: "#ffffff",
        "popover-foreground": "#501854",
        primary: "#a84370",
        "primary-foreground": "#ffffff",
        secondary: "#f1c4e6",
        "secondary-foreground": "#77347c",
        muted: "#f6e5f3",
        "muted-foreground": "#834588",
        accent: "#f1c4e6",
        "accent-foreground": "#77347c",
        destructive: "#ab4347",
        "destructive-foreground": "#ffffff",
        border: "#efbdeb",
        input: "#e7c1dc",
        ring: "#db2777",
        "chart-1": "#d926a2",
        "chart-2": "#6c12b9",
        "chart-3": "#274754",
        "chart-4": "#e8c468",
        "chart-5": "#f4a462",
        sidebar: "#f3e4f6",
        "sidebar-foreground": "#ac1668",
        "sidebar-primary": "#454554",
        "sidebar-primary-foreground": "#faf1f7",
        "sidebar-accent": "#f8f8f7",
        "sidebar-accent-foreground": "#454554",
        "sidebar-border": "#eceae9",
        "sidebar-ring": "#db2777",
        radius: "0.5rem",
      },
      dark: {
        background: "#221d27",
        foreground: "#d2c4de",
        card: "#2c2632",
        "card-foreground": "#dbc5d2",
        popover: "#100a0e",
        "popover-foreground": "#f8f1f5",
        primary: "#a3004c",
        "primary-foreground": "#efc0d8",
        secondary: "#362d3d",
        "secondary-foreground": "#d4c7e1",
        muted: "#28222d",
        "muted-foreground": "#c2b6cf",
        accent: "#463753",
        "accent-foreground": "#f8f1f5",
        destructive: "#301015",
        "destructive-foreground": "#ffffff",
        border: "#3b3237",
        input: "#3e343c",
        ring: "#db2777",
        "chart-1": "#a84370",
        "chart-2": "#934dcb",
        "chart-3": "#e88c30",
        "chart-4": "#af57db",
        "chart-5": "#e23670",
        sidebar: "#181117",
        "sidebar-foreground": "#e0cad6",
        "sidebar-primary": "#1d4ed8",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#261922",
        "sidebar-accent-foreground": "#f4f4f5",
        "sidebar-border": "#000000",
        "sidebar-ring": "#db2777",
      },
    },
  },

  twitter: {
    label: "Twitter",
    createdAt: "2025-04-24",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#0f1419",
        card: "#f7f8f8",
        "card-foreground": "#0f1419",
        popover: "#ffffff",
        "popover-foreground": "#0f1419",
        primary: "#1e9df1",
        "primary-foreground": "#ffffff",
        secondary: "#0f1419",
        "secondary-foreground": "#ffffff",
        muted: "#E5E5E6",
        "muted-foreground": "#0f1419",
        accent: "#E3ECF6",
        "accent-foreground": "#1e9df1",
        destructive: "#f4212e",
        "destructive-foreground": "#ffffff",
        border: "#e1eaef",
        input: "#f7f9fa",
        ring: "#1da1f2",
        "chart-1": "#1e9df1",
        "chart-2": "#00b87a",
        "chart-3": "#f7b928",
        "chart-4": "#17bf63",
        "chart-5": "#e0245e",
        sidebar: "#f7f8f8",
        "sidebar-foreground": "#0f1419",
        "sidebar-primary": "#1e9df1",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#E3ECF6",
        "sidebar-accent-foreground": "#1e9df1",
        "sidebar-border": "#e1e8ed",
        "sidebar-ring": "#1da1f2",
        "font-sans": "Open Sans, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Menlo, monospace",
        radius: "1.3rem",
        "shadow-color": "rgba(29,161,242,0.15)",
        "shadow-opacity": "0",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
      },
      dark: {
        background: "#000000",
        foreground: "#e7e9ea",
        card: "#17181c",
        "card-foreground": "#d9d9d9",
        popover: "#000000",
        "popover-foreground": "#e7e9ea",
        primary: "#1c9cf0",
        "primary-foreground": "#ffffff",
        secondary: "#f0f3f4",
        "secondary-foreground": "#0f1419",
        muted: "#181818",
        "muted-foreground": "#72767a",
        accent: "#061622",
        "accent-foreground": "#1c9cf0",
        destructive: "#f4212e",
        "destructive-foreground": "#ffffff",
        border: "#242628",
        input: "#22303c",
        ring: "#1da1f2",
        "chart-1": "#1e9df1",
        "chart-2": "#00b87a",
        "chart-3": "#f7b928",
        "chart-4": "#17bf63",
        "chart-5": "#e0245e",
        sidebar: "#17181c",
        "sidebar-foreground": "#d9d9d9",
        "sidebar-primary": "#1da1f2",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#061622",
        "sidebar-accent-foreground": "#1c9cf0",
        "sidebar-border": "#38444d",
        "sidebar-ring": "#1da1f2",
        "shadow-color": "rgba(29,161,242,0.25)",
      },
    },
  },

  "mocha-mousse": {
    label: "Mocha Mousse",
    createdAt: "2025-04-24",
    styles: {
      light: {
        background: "#F1F0E5",
        foreground: "#56453F",
        card: "#F1F0E5",
        "card-foreground": "#56453F",
        popover: "#FFFFFF",
        "popover-foreground": "#56453F",
        primary: "#A37764",
        "primary-foreground": "#FFFFFF",
        secondary: "#BAAB92",
        "secondary-foreground": "#ffffff",
        muted: "#E4C7B8",
        "muted-foreground": "#8A655A",
        accent: "#E4C7B8",
        "accent-foreground": "#56453F",
        destructive: "#1f1a17",
        "destructive-foreground": "#FFFFFF",
        border: "#BAAB92",
        input: "#BAAB92",
        ring: "#A37764",
        "chart-1": "#A37764",
        "chart-2": "#8A655A",
        "chart-3": "#C39E88",
        "chart-4": "#BAAB92",
        "chart-5": "#A28777",
        sidebar: "#ebd6cb",
        "sidebar-foreground": "#56453F",
        "sidebar-primary": "#A37764",
        "sidebar-primary-foreground": "#FFFFFF",
        "sidebar-accent": "#C39E88",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#A28777",
        "sidebar-ring": "#A37764",
        "font-sans": "DM Sans, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Menlo, monospace",
        radius: "0.5rem",
        "shadow-color": "hsl(20 18% 51% / 0.4)",
        "shadow-opacity": "0.11",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "2px",
        "shadow-offset-y": "2px",
      },
      dark: {
        background: "#2d2521",
        foreground: "#F1F0E5",
        card: "#3c332e",
        "card-foreground": "#F1F0E5",
        popover: "#3c332e",
        "popover-foreground": "#F1F0E5",
        primary: "#C39E88",
        "primary-foreground": "#2d2521",
        secondary: "#8A655A",
        "secondary-foreground": "#F1F0E5",
        muted: "#56453F",
        "muted-foreground": "#c5aa9b",
        accent: "#BAAB92",
        "accent-foreground": "#2d2521",
        destructive: "#E57373",
        "destructive-foreground": "#2d2521",
        border: "#56453F",
        input: "#56453F",
        ring: "#C39E88",
        "chart-1": "#C39E88",
        "chart-2": "#BAAB92",
        "chart-3": "#A37764",
        "chart-4": "#8A655A",
        "chart-5": "#A28777",
        sidebar: "#1f1a17",
        "sidebar-foreground": "#F1F0E5",
        "sidebar-primary": "#C39E88",
        "sidebar-primary-foreground": "#1f1a17",
        "sidebar-accent": "#BAAB92",
        "sidebar-accent-foreground": "#1f1a17",
        "sidebar-border": "#56453F",
        "sidebar-ring": "#C39E88",
        "shadow-color": "hsl(20 18% 30% / 0.5)",
      },
    },
  },

  bubblegum: {
    label: "Bubblegum",
    createdAt: "2025-04-18",
    styles: {
      light: {
        background: "#f6e6ee",
        foreground: "#5b5b5b",
        card: "#fdedc9",
        "card-foreground": "#5b5b5b",
        popover: "#ffffff",
        "popover-foreground": "#5b5b5b",
        primary: "#d04f99",
        "primary-foreground": "#ffffff",
        secondary: "#8acfd1",
        "secondary-foreground": "#333333",
        muted: "#b2e1eb",
        "muted-foreground": "#7a7a7a",
        accent: "#fbe2a7",
        "accent-foreground": "#333333",
        destructive: "#f96f70",
        "destructive-foreground": "#ffffff",
        border: "#d04f99",
        input: "#e4e4e4",
        ring: "#e670ab",
        "chart-1": "#e670ab",
        "chart-2": "#84d2e2",
        "chart-3": "#fbe2a7",
        "chart-4": "#f3a0ca",
        "chart-5": "#d7488e",
        sidebar: "#f8d8ea",
        "sidebar-foreground": "#333333",
        "sidebar-primary": "#ec4899",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f9a8d4",
        "sidebar-accent-foreground": "#333333",
        "sidebar-border": "#f3e8ff",
        "sidebar-ring": "#ec4899",
        "font-sans": "Poppins, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "Fira Code, monospace",
        radius: "0.4rem",
        "shadow-color": "hsl(325.78 58.18% 56.86% / 0.5)",
        "shadow-opacity": "1.0",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "3px",
        "shadow-offset-y": "3px",
      },
      dark: {
        background: "#12242e",
        foreground: "#f3e3ea",
        card: "#1c2e38",
        "card-foreground": "#f3e3ea",
        popover: "#1c2e38",
        "popover-foreground": "#f3e3ea",
        primary: "#fbe2a7",
        "primary-foreground": "#12242e",
        secondary: "#e4a2b1",
        "secondary-foreground": "#12242e",
        muted: "#24272b",
        "muted-foreground": "#e4a2b1",
        accent: "#c67b96",
        "accent-foreground": "#f3e3ea",
        destructive: "#e35ea4",
        "destructive-foreground": "#12242e",
        border: "#324859",
        input: "#20333d",
        ring: "#50afb6",
        "chart-1": "#50afb6",
        "chart-2": "#e4a2b1",
        "chart-3": "#c67b96",
        "chart-4": "#175c6c",
        "chart-5": "#24272b",
        sidebar: "#101f28",
        "sidebar-foreground": "#f3f4f6",
        "sidebar-primary": "#ec4899",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f9a8d4",
        "sidebar-accent-foreground": "#1f2937",
        "sidebar-border": "#374151",
        "sidebar-ring": "#ec4899",
        "font-sans": "Poppins, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "Fira Code, monospace",
        "shadow-color": "#324859",
      },
    },
  },
  "amethyst-haze": {
    label: "Amethyst Haze",
    createdAt: "2025-05-08",
    styles: {
      light: {
        background: "#f8f7fa",
        foreground: "#3d3c4f",
        card: "#ffffff",
        "card-foreground": "#3d3c4f",
        popover: "#ffffff",
        "popover-foreground": "#3d3c4f",
        primary: "#8a79ab",
        "primary-foreground": "#f8f7fa",
        secondary: "#dfd9ec",
        "secondary-foreground": "#3d3c4f",
        muted: "#dcd9e3",
        "muted-foreground": "#6b6880",
        accent: "#e6a5b8",
        "accent-foreground": "#4b2e36",
        destructive: "#d95c5c",
        "destructive-foreground": "#f8f7fa",
        border: "#cec9d9",
        input: "#eae7f0",
        ring: "#8a79ab",
        "chart-1": "#8a79ab",
        "chart-2": "#e6a5b8",
        "chart-3": "#77b8a1",
        "chart-4": "#f0c88d",
        "chart-5": "#a0bbe3",
        sidebar: "#f1eff5",
        "sidebar-foreground": "#3d3c4f",
        "sidebar-primary": "#8a79ab",
        "sidebar-primary-foreground": "#f8f7fa",
        "sidebar-accent": "#e6a5b8",
        "sidebar-accent-foreground": "#4b2e36",
        "sidebar-border": "#d7d2e0",
        "sidebar-ring": "#8a79ab",
        "font-sans": "Geist, sans-serif",
        "font-serif": '"Lora", Georgia, serif',
        "font-mono": '"Fira Code", "Courier New", monospace',
        radius: "0.5rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.06",
        "shadow-blur": "5px",
        "shadow-spread": "1px",
        "shadow-offset-x": "1px",
        "shadow-offset-y": "2px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1a1823",
        foreground: "#e0ddef",
        card: "#232030",
        "card-foreground": "#e0ddef",
        popover: "#232030",
        "popover-foreground": "#e0ddef",
        primary: "#a995c9",
        "primary-foreground": "#1a1823",
        secondary: "#5a5370",
        "secondary-foreground": "#e0ddef",
        muted: "#242031",
        "muted-foreground": "#a09aad",
        accent: "#372e3f",
        "accent-foreground": "#f2b8c6",
        destructive: "#e57373",
        "destructive-foreground": "#1a1823",
        border: "#302c40",
        input: "#2a273a",
        ring: "#a995c9",
        "chart-1": "#a995c9",
        "chart-2": "#f2b8c6",
        "chart-3": "#77b8a1",
        "chart-4": "#f0c88d",
        "chart-5": "#a0bbe3",
        sidebar: "#16141e",
        "sidebar-foreground": "#e0ddef",
        "sidebar-primary": "#a995c9",
        "sidebar-primary-foreground": "#1a1823",
        "sidebar-accent": "#372e3f",
        "sidebar-accent-foreground": "#f2b8c6",
        "sidebar-border": "#2a273a",
        "sidebar-ring": "#a995c9",
      },
    },
  },

  notebook: {
    label: "Notebook",
    createdAt: "2025-05-10",
    styles: {
      light: {
        background: "#f9f9f9",
        foreground: "#3a3a3a",
        card: "#ffffff",
        "card-foreground": "#3a3a3a",
        popover: "#ffffff",
        "popover-foreground": "#3a3a3a",
        primary: "#606060",
        "primary-foreground": "#f0f0f0",
        secondary: "#dedede",
        "secondary-foreground": "#3a3a3a",
        muted: "#e3e3e3",
        "muted-foreground": "#505050",
        accent: "#f3eac8",
        "accent-foreground": "#5d4037",
        destructive: "#c87a7a",
        "destructive-foreground": "#ffffff",
        border: "#747272",
        input: "#ffffff",
        ring: "#a0a0a0",
        "chart-1": "#333333",
        "chart-2": "#555555",
        "chart-3": "#777777",
        "chart-4": "#999999",
        "chart-5": "#bbbbbb",
        sidebar: "#f0f0f0",
        "sidebar-foreground": "#3a3a3a",
        "sidebar-primary": "#606060",
        "sidebar-primary-foreground": "#f0f0f0",
        "sidebar-accent": "#f3eac8",
        "sidebar-accent-foreground": "#5d4037",
        "sidebar-border": "#c0c0c0",
        "sidebar-ring": "#a0a0a0",
        "font-sans": "Architects Daughter, sans-serif",
        "font-serif": '"Times New Roman", Times, serif',
        "font-mono": '"Courier New", Courier, monospace',
        radius: "0.625rem",
        "shadow-color": "#000000",
        "shadow-opacity": "0.03",
        "shadow-blur": "5px",
        "shadow-spread": "0px",
        "shadow-offset-x": "1px",
        "shadow-offset-y": "4px",
        "letter-spacing": "0.5px",
        spacing: "0.25rem",
      },
      dark: {
        background: "#2b2b2b",
        foreground: "#dcdcdc",
        card: "#333333",
        "card-foreground": "#dcdcdc",
        popover: "#333333",
        "popover-foreground": "#dcdcdc",
        primary: "#b0b0b0",
        "primary-foreground": "#2b2b2b",
        secondary: "#5a5a5a",
        "secondary-foreground": "#c0c0c0",
        muted: "#454545",
        "muted-foreground": "#a0a0a0",
        accent: "#e0e0e0",
        "accent-foreground": "#333333",
        destructive: "#d9afaf",
        "destructive-foreground": "#2b2b2b",
        border: "#4f4f4f",
        input: "#333333",
        ring: "#c0c0c0",
        "chart-1": "#efefef",
        "chart-2": "#d0d0d0",
        "chart-3": "#b0b0b0",
        "chart-4": "#909090",
        "chart-5": "#707070",
        sidebar: "#212121",
        "sidebar-foreground": "#dcdcdc",
        "sidebar-primary": "#b0b0b0",
        "sidebar-primary-foreground": "#212121",
        "sidebar-accent": "#e0e0e0",
        "sidebar-accent-foreground": "#333333",
        "sidebar-border": "#4f4f4f",
        "sidebar-ring": "#c0c0c0",
        "font-sans": "Architects Daughter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": '"Fira Code", "Courier New", monospace',
        radius: "0.625rem",
        "shadow-color": "#000000",
        "shadow-opacity": "0.03",
        "shadow-blur": "5px",
        "shadow-spread": "0px",
        "shadow-offset-x": "1px",
        "shadow-offset-y": "4px",
        "letter-spacing": "0.5px",
        spacing: "0.25rem",
      },
    },
  },

  "doom-64": {
    label: "Doom 64",
    createdAt: "2025-04-28",
    styles: {
      light: {
        background: "#cccccc",
        foreground: "#1f1f1f",
        card: "#b0b0b0",
        "card-foreground": "#1f1f1f",
        popover: "#b0b0b0",
        "popover-foreground": "#1f1f1f",
        primary: "#b71c1c",
        "primary-foreground": "#ffffff",
        secondary: "#556b2f",
        "secondary-foreground": "#ffffff",
        muted: "#b8b8b8",
        "muted-foreground": "#4a4a4a",
        accent: "#4682b4",
        "accent-foreground": "#ffffff",
        destructive: "#ff6f00",
        "destructive-foreground": "#000000",
        border: "#505050",
        input: "#505050",
        ring: "#b71c1c",
        "chart-1": "#b71c1c",
        "chart-2": "#556b2f",
        "chart-3": "#4682b4",
        "chart-4": "#ff6f00",
        "chart-5": "#8d6e63",
        sidebar: "#b0b0b0",
        "sidebar-foreground": "#1f1f1f",
        "sidebar-primary": "#b71c1c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#4682b4",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#505050",
        "sidebar-ring": "#b71c1c",
        "font-sans": '"Oxanium", sans-serif',
        "font-serif": 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        "font-mono": '"Source Code Pro", monospace',
        radius: "0px",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.4",
        "shadow-blur": "4px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
      dark: {
        background: "#1a1a1a",
        foreground: "#e0e0e0",
        card: "#2a2a2a",
        "card-foreground": "#e0e0e0",
        popover: "#2a2a2a",
        "popover-foreground": "#e0e0e0",
        primary: "#e53935",
        "primary-foreground": "#ffffff",
        secondary: "#689f38",
        "secondary-foreground": "#000000",
        muted: "#252525",
        "muted-foreground": "#a0a0a0",
        accent: "#64b5f6",
        "accent-foreground": "#000000",
        destructive: "#ffa000",
        "destructive-foreground": "#000000",
        border: "#4a4a4a",
        input: "#4a4a4a",
        ring: "#e53935",
        "chart-1": "#e53935",
        "chart-2": "#689f38",
        "chart-3": "#64b5f6",
        "chart-4": "#ffa000",
        "chart-5": "#a1887f",
        sidebar: "#141414",
        "sidebar-foreground": "#e0e0e0",
        "sidebar-primary": "#e53935",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#64b5f6",
        "sidebar-accent-foreground": "#000000",
        "sidebar-border": "#4a4a4a",
        "sidebar-ring": "#e53935",
        "font-sans": '"Oxanium", sans-serif',
        "font-serif": 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        "font-mono": '"Source Code Pro", monospace',
        radius: "0px",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.6",
        "shadow-blur": "5px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
        "letter-spacing": "0em",
        spacing: "0.25rem",
      },
    },
  },

  catppuccin: {
    label: "Catppuccin",
    createdAt: "2025-04-18",
    styles: {
      light: {
        background: "#eff1f5",
        foreground: "#4c4f69",
        card: "#ffffff",
        "card-foreground": "#4c4f69",
        popover: "#ccd0da",
        "popover-foreground": "#4c4f69",
        primary: "#8839ef",
        "primary-foreground": "#ffffff",
        secondary: "#ccd0da",
        "secondary-foreground": "#4c4f69",
        muted: "#dce0e8",
        "muted-foreground": "#6c6f85",
        accent: "#04a5e5",
        "accent-foreground": "#ffffff",
        destructive: "#d20f39",
        "destructive-foreground": "#ffffff",
        border: "#bcc0cc",
        input: "#ccd0da",
        ring: "#8839ef",
        "chart-1": "#8839ef",
        "chart-2": "#04a5e5",
        "chart-3": "#40a02b",
        "chart-4": "#fe640b",
        "chart-5": "#dc8a78",
        sidebar: "#e6e9ef",
        "sidebar-foreground": "#4c4f69",
        "sidebar-primary": "#8839ef",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#04a5e5",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#bcc0cc",
        "sidebar-ring": "#8839ef",
        "font-sans": "Montserrat, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Fira Code, monospace",
        radius: "0.35rem",
        "shadow-color": "hsl(240 30% 25%)",
        "shadow-opacity": "0.12",
        "shadow-blur": "6px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
      },
      dark: {
        background: "#181825",
        foreground: "#cdd6f4",
        card: "#1e1e2e",
        "card-foreground": "#cdd6f4",
        popover: "#45475a",
        "popover-foreground": "#cdd6f4",
        primary: "#cba6f7",
        "primary-foreground": "#1e1e2e",
        secondary: "#585b70",
        "secondary-foreground": "#cdd6f4",
        muted: "#292c3c",
        "muted-foreground": "#a6adc8",
        accent: "#89dceb",
        "accent-foreground": "#1e1e2e",
        destructive: "#f38ba8",
        "destructive-foreground": "#1e1e2e",
        border: "#313244",
        input: "#313244",
        ring: "#cba6f7",
        "chart-1": "#cba6f7",
        "chart-2": "#89dceb",
        "chart-3": "#a6e3a1",
        "chart-4": "#fab387",
        "chart-5": "#f5e0dc",
        sidebar: "#11111b",
        "sidebar-foreground": "#cdd6f4",
        "sidebar-primary": "#cba6f7",
        "sidebar-primary-foreground": "#1e1e2e",
        "sidebar-accent": "#89dceb",
        "sidebar-accent-foreground": "#1e1e2e",
        "sidebar-border": "#45475a",
        "sidebar-ring": "#cba6f7",
      },
    },
  },

  graphite: {
    label: "Graphite",
    createdAt: "2025-04-17",
    styles: {
      light: {
        background: "#f0f0f0",
        foreground: "#333333",
        card: "#f5f5f5",
        "card-foreground": "#333333",
        popover: "#f5f5f5",
        "popover-foreground": "#333333",
        primary: "#606060",
        "primary-foreground": "#ffffff",
        secondary: "#e0e0e0",
        "secondary-foreground": "#333333",
        muted: "#d9d9d9",
        "muted-foreground": "#666666",
        accent: "#c0c0c0",
        "accent-foreground": "#333333",
        destructive: "#cc3333",
        "destructive-foreground": "#ffffff",
        border: "#d0d0d0",
        input: "#e0e0e0",
        ring: "#606060",
        "chart-1": "#606060",
        "chart-2": "#476666",
        "chart-3": "#909090",
        "chart-4": "#a8a8a8",
        "chart-5": "#c0c0c0",
        sidebar: "#eaeaea",
        "sidebar-foreground": "#333333",
        "sidebar-primary": "#606060",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#c0c0c0",
        "sidebar-accent-foreground": "#333333",
        "sidebar-border": "#d0d0d0",
        "sidebar-ring": "#606060",
        "font-sans": "Montserrat, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Fira Code, monospace",
        radius: "0.35rem",
        "shadow-color": "hsl(0 0% 20% / 0.1)",
        "shadow-opacity": "0.15",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
      },
      dark: {
        background: "#1a1a1a",
        foreground: "#d9d9d9",
        card: "#202020",
        "card-foreground": "#d9d9d9",
        popover: "#202020",
        "popover-foreground": "#d9d9d9",
        primary: "#a0a0a0",
        "primary-foreground": "#1a1a1a",
        secondary: "#303030",
        "secondary-foreground": "#d9d9d9",
        muted: "#2a2a2a",
        "muted-foreground": "#808080",
        accent: "#404040",
        "accent-foreground": "#d9d9d9",
        destructive: "#e06666",
        "destructive-foreground": "#ffffff",
        border: "#353535",
        input: "#303030",
        ring: "#a0a0a0",
        "chart-1": "#a0a0a0",
        "chart-2": "#7e9ca0",
        "chart-3": "#707070",
        "chart-4": "#585858",
        "chart-5": "#404040",
        sidebar: "#1f1f1f",
        "sidebar-foreground": "#d9d9d9",
        "sidebar-primary": "#a0a0a0",
        "sidebar-primary-foreground": "#1a1a1a",
        "sidebar-accent": "#404040",
        "sidebar-accent-foreground": "#d9d9d9",
        "sidebar-border": "#353535",
        "sidebar-ring": "#a0a0a0",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Fira Code, monospace",
      },
    },
  },

  perpetuity: {
    label: "Perpetuity",
    createdAt: "2025-04-01",
    styles: {
      light: {
        background: "#e8f0f0",
        foreground: "#0a4a55",
        card: "#f2f7f7",
        "card-foreground": "#0a4a55",
        popover: "#f2f7f7",
        "popover-foreground": "#0a4a55",
        primary: "#06858e",
        "primary-foreground": "#ffffff",
        secondary: "#d9eaea",
        "secondary-foreground": "#0a4a55",
        muted: "#e0eaea",
        "muted-foreground": "#427a7e",
        accent: "#c9e5e7",
        "accent-foreground": "#0a4a55",
        destructive: "#d13838",
        "destructive-foreground": "#ffffff",
        border: "#cde0e2",
        input: "#d9eaea",
        ring: "#06858e",
        "chart-1": "#06858e",
        "chart-2": "#1e9ea6",
        "chart-3": "#37b6be",
        "chart-4": "#5dc7ce",
        "chart-5": "#8ad8dd",
        sidebar: "#daebed",
        "sidebar-foreground": "#0a4a55",
        "sidebar-primary": "#06858e",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#c9e5e7",
        "sidebar-accent-foreground": "#0a4a55",
        "sidebar-border": "#cde0e2",
        "sidebar-ring": "#06858e",
        "font-sans": "Courier New, monospace",
        "font-serif": "Courier New, monospace",
        "font-mono": "Courier New, monospace",
        radius: "0.125rem",
        "shadow-color": "hsl(185 70% 30% / 0.15)",
        "shadow-opacity": "0.15",
        "shadow-blur": "2px",
        "shadow-spread": "0px",
        "shadow-offset-x": "1px",
        "shadow-offset-y": "1px",
      },
      dark: {
        background: "#0a1a20",
        foreground: "#4de8e8",
        card: "#0c2025",
        "card-foreground": "#4de8e8",
        popover: "#0c2025",
        "popover-foreground": "#4de8e8",
        primary: "#4de8e8",
        "primary-foreground": "#0a1a20",
        secondary: "#164955",
        "secondary-foreground": "#4de8e8",
        muted: "#0f3039",
        "muted-foreground": "#36a5a5",
        accent: "#164955",
        "accent-foreground": "#4de8e8",
        destructive: "#e83c3c",
        "destructive-foreground": "#f2f2f2",
        border: "#164955",
        input: "#164955",
        ring: "#4de8e8",
        "chart-1": "#4de8e8",
        "chart-2": "#36a5a5",
        "chart-3": "#2d8a8a",
        "chart-4": "#19595e",
        "chart-5": "#0e383c",
        sidebar: "#0a1a20",
        "sidebar-foreground": "#4de8e8",
        "sidebar-primary": "#4de8e8",
        "sidebar-primary-foreground": "#0a1a20",
        "sidebar-accent": "#164955",
        "sidebar-accent-foreground": "#4de8e8",
        "sidebar-border": "#164955",
        "sidebar-ring": "#4de8e8",
        "font-sans": "Source Code Pro, monospace",
        "font-serif": "Source Code Pro, monospace",
        "font-mono": "Source Code Pro, monospace",
        radius: "0.125rem",
        "shadow-color": "hsl(180 70% 60% / 0.2)",
        "shadow-opacity": "0.2",
        "shadow-blur": "2px",
        "shadow-spread": "0px",
        "shadow-offset-x": "1px",
        "shadow-offset-y": "1px",
      },
    },
  },
  "kodama-grove": {
    label: "Kodama Grove",
    styles: {
      light: {
        background: "#e4d7b0",
        foreground: "#5c4b3e",
        card: "#e7dbbf",
        "card-foreground": "#5c4b3e",
        popover: "#f3ead2",
        "popover-foreground": "#5c4b3e",
        primary: "#8d9d4f",
        "primary-foreground": "#fdfbf6",
        secondary: "#decea0",
        "secondary-foreground": "#5c4b3e",
        muted: "#decea0",
        "muted-foreground": "#85766a",
        accent: "#dbc894",
        "accent-foreground": "#5c4b3e",
        destructive: "#d98b7e",
        "destructive-foreground": "#faf8f2",
        border: "#b19681",
        input: "#dbc894",
        ring: "#9db18c",
        "chart-1": "#9db18c",
        "chart-2": "#8a9f7b",
        "chart-3": "#bac9b4",
        "chart-4": "#71856a",
        "chart-5": "#5e6e58",
        sidebar: "#e2d1a2",
        "sidebar-foreground": "#5c4b3e",
        "sidebar-primary": "#9db18c",
        "sidebar-primary-foreground": "#fdfbf6",
        "sidebar-accent": "#eae5d9",
        "sidebar-accent-foreground": "#5c4b3e",
        "sidebar-border": "#e5e0d4",
        "sidebar-ring": "#9db18c",
        "font-sans": "Merriweather, serif",
        "font-serif": "Source Serif 4, serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.425rem",
        "shadow-color": "hsl(88 22% 35% / 0.15)",
        "shadow-opacity": "0.15",
        "shadow-blur": "2px",
        "shadow-spread": "0px",
        "shadow-offset-x": "3px",
        "shadow-offset-y": "3px",
      },
      dark: {
        background: "#3a3529",
        foreground: "#ede4d4",
        card: "#413c33",
        "card-foreground": "#ede4d4",
        popover: "#413c33",
        "popover-foreground": "#ede4d4",
        primary: "#8a9f7b",
        "primary-foreground": "#2a2521",
        secondary: "#5a5345",
        "secondary-foreground": "#ede4d4",
        muted: "#4a4439",
        "muted-foreground": "#a8a096",
        accent: "#a18f5c",
        "accent-foreground": "#2a2521",
        destructive: "#b5766a",
        "destructive-foreground": "#f0e9db",
        border: "#5a5345",
        input: "#5a5345",
        ring: "#8a9f7b",
        "chart-1": "#8a9f7b",
        "chart-2": "#9db18c",
        "chart-3": "#71856a",
        "chart-4": "#a18f5c",
        "chart-5": "#5e6e58",
        sidebar: "#3a3529",
        "sidebar-foreground": "#ede4d4",
        "sidebar-primary": "#8a9f7b",
        "sidebar-primary-foreground": "#2a2521",
        "sidebar-accent": "#a18f5c",
        "sidebar-accent-foreground": "#2a2a2521",
        "sidebar-border": "#5a5345",
        "sidebar-ring": "#8a9f7b",
      },
    },
  },
  "cosmic-night": {
    label: "Cosmic Night",
    createdAt: "2025-05-30",
    styles: {
      light: {
        background: "#f0f2f5",
        foreground: "#1c1e21",
        card: "#ffffff",
        "card-foreground": "#1c1e21",
        popover: "#ffffff",
        "popover-foreground": "#1c1e21",
        primary: "#1877f2",
        "primary-foreground": "#ffffff",
        secondary: "#e4e6eb",
        "secondary-foreground": "#050505",
        muted: "#f0f2f5",
        "muted-foreground": "#65676b",
        accent: "#e7f3ff",
        "accent-foreground": "#1877f2",
        destructive: "#fa3e3e",
        "destructive-foreground": "#ffffff",
        border: "#ccd0d5",
        input: "#f0f2f5",
        ring: "#1877f2",
        "chart-1": "#1877f2",
        "chart-2": "#42b3f4",
        "chart-3": "#2eb67d",
        "chart-4": "#ecb22e",
        "chart-5": "#e01e5a",
        radius: "0.25rem",
        sidebar: "#f0f2f5",
        "sidebar-foreground": "#1c1e21",
        "sidebar-primary": "#1877f2",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e7f3ff",
        "sidebar-accent-foreground": "#1877f2",
        "sidebar-border": "#ccd0d5",
        "sidebar-ring": "#1877f2",
      },
      dark: {
        background: "#18191a",
        foreground: "#e4e6eb",
        card: "#242526",
        "card-foreground": "#e4e6eb",
        popover: "#242526",
        "popover-foreground": "#e4e6eb",
        primary: "#2d88ff",
        "primary-foreground": "#ffffff",
        secondary: "#3a3b3c",
        "secondary-foreground": "#e4e6eb",
        muted: "#3a3b3c",
        "muted-foreground": "#b0b3b8",
        accent: "#263951",
        "accent-foreground": "#2d88ff",
        destructive: "#fa3e3e",
        "destructive-foreground": "#ffffff",
        border: "#3e4042",
        input: "#3a3b3c",
        ring: "#2d88ff",
        "chart-1": "#2d88ff",
        "chart-2": "#42b3f4",
        "chart-3": "#2eb67d",
        "chart-4": "#ecb22e",
        "chart-5": "#e01e5a",
        radius: "0.25rem",
        sidebar: "#18191a",
        "sidebar-foreground": "#e4e6eb",
        "sidebar-primary": "#2d88ff",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#263951",
        "sidebar-accent-foreground": "#2d88ff",
        "sidebar-border": "#3e4042",
        "sidebar-ring": "#2d88ff",
      },
    },
  },

  tangerine: {
    label: "Tangerine",
    createdAt: "2025-05-15",
    styles: {
      light: {
        background: "#fff9f5",
        foreground: "#4a2a1a",
        card: "#ffffff",
        "card-foreground": "#4a2a1a",
        popover: "#ffffff",
        "popover-foreground": "#4a2a1a",
        primary: "#ff8c00",
        "primary-foreground": "#ffffff",
        secondary: "#ffd8a8",
        "secondary-foreground": "#4a2a1a",
        muted: "#ffe8cc",
        "muted-foreground": "#8a664e",
        accent: "#ff922b",
        "accent-foreground": "#ffffff",
        destructive: "#e03131",
        "destructive-foreground": "#ffffff",
        border: "#ffd8a8",
        input: "#ffe8cc",
        ring: "#ff8c00",
        "chart-1": "#ff8c00",
        "chart-2": "#ff922b",
        "chart-3": "#ffa94d",
        "chart-4": "#ffc078",
        "chart-5": "#ffd8a8",
        radius: "0.75rem",
      },
      dark: {
        background: "#1f140a",
        foreground: "#ffd8a8",
        card: "#2e1e0f",
        "card-foreground": "#ffd8a8",
        popover: "#2e1e0f",
        "popover-foreground": "#ffd8a8",
        primary: "#ff922b",
        "primary-foreground": "#1f140a",
        secondary: "#4a2a1a",
        "secondary-foreground": "#ffd8a8",
        muted: "#2e1e0f",
        "muted-foreground": "#8a664e",
        accent: "#ff8c00",
        "accent-foreground": "#ffffff",
        destructive: "#ff6b6b",
        "destructive-foreground": "#ffffff",
        border: "#4a2a1a",
        input: "#4a2a1a",
        ring: "#ff922b",
        "chart-1": "#ff922b",
        "chart-2": "#ff8c00",
        "chart-3": "#e8590c",
        "chart-4": "#d9480f",
        "chart-5": "#bc3908",
        radius: "0.75rem",
      },
    },
  },

  "quantum-rose": {
    label: "Quantum Rose",
    createdAt: "2025-05-12",
    styles: {
      light: {
        background: "#fff5f7",
        foreground: "#4a0e1c",
        card: "#ffffff",
        "card-foreground": "#4a0e1c",
        popover: "#ffffff",
        "popover-foreground": "#4a0e1c",
        primary: "#e91e63",
        "primary-foreground": "#ffffff",
        secondary: "#fce4ec",
        "secondary-foreground": "#c2185b",
        muted: "#f8bbd0",
        "muted-foreground": "#880e4f",
        accent: "#ff4081",
        "accent-foreground": "#ffffff",
        destructive: "#d32f2f",
        "destructive-foreground": "#ffffff",
        border: "#f8bbd0",
        input: "#fce4ec",
        ring: "#e91e63",
        "chart-1": "#e91e63",
        "chart-2": "#f06292",
        "chart-3": "#ba68c8",
        "chart-4": "#9c27b0",
        "chart-5": "#673ab7",
        radius: "1rem",
      },
      dark: {
        background: "#1a050a",
        foreground: "#fce4ec",
        card: "#2d0a14",
        "card-foreground": "#fce4ec",
        popover: "#2d0a14",
        "popover-foreground": "#fce4ec",
        primary: "#ff4081",
        "primary-foreground": "#ffffff",
        secondary: "#4a0e1c",
        "secondary-foreground": "#fce4ec",
        muted: "#2d0a14",
        "muted-foreground": "#c2185b",
        accent: "#e91e63",
        "accent-foreground": "#ffffff",
        destructive: "#ef5350",
        "destructive-foreground": "#ffffff",
        border: "#4a0e1c",
        input: "#4a0e1c",
        ring: "#ff4081",
        "chart-1": "#ff4081",
        "chart-2": "#e91e63",
        "chart-3": "#d81b60",
        "chart-4": "#c2185b",
        "chart-5": "#ad1457",
        radius: "1rem",
      },
    },
  },

  nature: {
    label: "Nature",
    createdAt: "2025-04-14",
    styles: {
      light: {
        background: "#fdfdfb",
        foreground: "#1c2a1e",
        card: "#ffffff",
        "card-foreground": "#1c2a1e",
        popover: "#ffffff",
        "popover-foreground": "#1c2a1e",
        primary: "#2e7d32",
        "primary-foreground": "#ffffff",
        secondary: "#edeadf",
        "secondary-foreground": "#1c2a1e",
        muted: "#f1f0e7",
        "muted-foreground": "#4b5e4d",
        accent: "#8bc34a",
        "accent-foreground": "#ffffff",
        destructive: "#c62828",
        "destructive-foreground": "#ffffff",
        border: "#dce2dc",
        input: "#eef2ee",
        ring: "#2e7d32",
        "chart-1": "#2e7d32",
        "chart-2": "#689f38",
        "chart-3": "#9ccc65",
        "chart-4": "#dce775",
        "chart-5": "#fff176",
        sidebar: "#f5f7f5",
        "sidebar-foreground": "#1c2a1e",
        "sidebar-primary": "#2e7d32",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e8f5e9",
        "sidebar-accent-foreground": "#1c2a1e",
        "sidebar-border": "#dce2dc",
        "sidebar-ring": "#2e7d32",
        radius: "0.25rem",
      },
      dark: {
        background: "#0c140d",
        foreground: "#dce2dc",
        card: "#152016",
        "card-foreground": "#dce2dc",
        popover: "#152016",
        "popover-foreground": "#dce2dc",
        primary: "#4caf50",
        "primary-foreground": "#0c140d",
        secondary: "#263238",
        "secondary-foreground": "#dce2dc",
        muted: "#1c2a1e",
        "muted-foreground": "#81c784",
        accent: "#8bc34a",
        "accent-foreground": "#0c140d",
        destructive: "#e57373",
        "destructive-foreground": "#0c140d",
        border: "#2e3d30",
        input: "#1c2a1e",
        ring: "#4caf50",
        "chart-1": "#4caf50",
        "chart-2": "#8bc34a",
        "chart-3": "#cddc39",
        "chart-4": "#ffeb3b",
        "chart-5": "#ffc107",
        sidebar: "#0c140d",
        "sidebar-foreground": "#dce2dc",
        "sidebar-primary": "#4caf50",
        "sidebar-primary-foreground": "#0c140d",
        "sidebar-accent": "#1b2e1e",
        "sidebar-accent-foreground": "#dce2dc",
        "sidebar-border": "#2e3d30",
        "sidebar-ring": "#4caf50",
        radius: "0.25rem",
      },
    },
  },

  "bold-tech": {
    label: "Bold Tech",
    createdAt: "2025-04-12",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#f4f4f4",
        "card-foreground": "#000000",
        popover: "#ffffff",
        "popover-foreground": "#000000",
        primary: "#ec4899",
        "primary-foreground": "#ffffff",
        secondary: "#000000",
        "secondary-foreground": "#ffffff",
        muted: "#e2e2e2",
        "muted-foreground": "#525252",
        accent: "#f472b6",
        "accent-foreground": "#ffffff",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#000000",
        input: "#e2e2e2",
        ring: "#000000",
        "chart-1": "#ec4899",
        "chart-2": "#000000",
        "chart-3": "#525252",
        "chart-4": "#a1a1a1",
        "chart-5": "#d4d4d4",
        sidebar: "#f4f4f4",
        "sidebar-foreground": "#000000",
        "sidebar-primary": "#ec4899",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e2e2e2",
        "sidebar-accent-foreground": "#000000",
        "sidebar-border": "#000000",
        "sidebar-ring": "#000000",
        radius: "0px",
      },
      dark: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#121212",
        "card-foreground": "#ffffff",
        popover: "#000000",
        "popover-foreground": "#ffffff",
        primary: "#ec4899",
        "primary-foreground": "#000000",
        secondary: "#ffffff",
        "secondary-foreground": "#000000",
        muted: "#262626",
        "muted-foreground": "#a1a1a1",
        accent: "#f472b6",
        "accent-foreground": "#000000",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#ffffff",
        input: "#262626",
        ring: "#ffffff",
        "chart-1": "#ec4899",
        "chart-2": "#ffffff",
        "chart-3": "#a1a1a1",
        "chart-4": "#525252",
        "chart-5": "#262626",
        sidebar: "#121212",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#ec4899",
        "sidebar-primary-foreground": "#000000",
        "sidebar-accent": "#262626",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#ffffff",
        "sidebar-ring": "#ffffff",
        radius: "0px",
      },
    },
  },

  "elegant-luxury": {
    label: "Elegant Luxury",
    createdAt: "2025-04-10",
    styles: {
      light: {
        background: "#faf9f6",
        foreground: "#1a1a1a",
        card: "#ffffff",
        "card-foreground": "#1a1a1a",
        popover: "#ffffff",
        "popover-foreground": "#1a1a1a",
        primary: "#b59d5f",
        "primary-foreground": "#ffffff",
        secondary: "#eae7e0",
        "secondary-foreground": "#1a1a1a",
        muted: "#f2f0ea",
        "muted-foreground": "#7a766c",
        accent: "#d4c8a8",
        "accent-foreground": "#1a1a1a",
        destructive: "#8b2e2e",
        "destructive-foreground": "#ffffff",
        border: "#e5e1d8",
        input: "#f2f0ea",
        ring: "#b59d5f",
        "chart-1": "#b59d5f",
        "chart-2": "#8c7a4a",
        "chart-3": "#d4c8a8",
        "chart-4": "#1a1a1a",
        "chart-5": "#7a766c",
        sidebar: "#f5f3f0",
        "sidebar-foreground": "#1a1a1a",
        "sidebar-primary": "#b59d5f",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#eae7e0",
        "sidebar-accent-foreground": "#1a1a1a",
        "sidebar-border": "#e5e1d8",
        "sidebar-ring": "#b59d5f",
        radius: "0.25rem",
      },
      dark: {
        background: "#0f0f0e",
        foreground: "#e5e1d8",
        card: "#1a1a19",
        "card-foreground": "#e5e1d8",
        popover: "#1a1a19",
        "popover-foreground": "#e5e1d8",
        primary: "#b59d5f",
        "primary-foreground": "#0f0f0e",
        secondary: "#2d2d2b",
        "secondary-foreground": "#e5e1d8",
        muted: "#1f1f1d",
        "muted-foreground": "#a39f93",
        accent: "#8c7a4a",
        "accent-foreground": "#ffffff",
        destructive: "#e57373",
        "destructive-foreground": "#0f0f0e",
        border: "#2d2d2b",
        input: "#1f1f1d",
        ring: "#b59d5f",
        "chart-1": "#b59d5f",
        "chart-2": "#d4c8a8",
        "chart-3": "#8c7a4a",
        "chart-4": "#e5e1d8",
        "chart-5": "#7a766c",
        sidebar: "#0f0f0e",
        "sidebar-foreground": "#e5e1d8",
        "sidebar-primary": "#b59d5f",
        "sidebar-primary-foreground": "#0f0f0e",
        "sidebar-accent": "#2d2d2b",
        "sidebar-accent-foreground": "#e5e1d8",
        "sidebar-border": "#2d2d2b",
        "sidebar-ring": "#b59d5f",
        radius: "0.25rem",
      },
    },
  },

  "amber-minimal": {
    label: "Amber Minimal",
    createdAt: "2025-04-06",
    styles: {
      light: {
        background: "#fffbeb",
        foreground: "#451a03",
        card: "#ffffff",
        "card-foreground": "#451a03",
        popover: "#ffffff",
        "popover-foreground": "#451a03",
        primary: "#d97706",
        "primary-foreground": "#ffffff",
        secondary: "#fef3c7",
        "secondary-foreground": "#92400e",
        muted: "#fef3c7",
        "muted-foreground": "#b45309",
        accent: "#fbbf24",
        "accent-foreground": "#78350f",
        destructive: "#b91c1c",
        "destructive-foreground": "#ffffff",
        border: "#fcd34d",
        input: "#fde68a",
        ring: "#d97706",
        "chart-1": "#d97706",
        "chart-2": "#fbbf24",
        "chart-3": "#f59e0b",
        "chart-4": "#d97706",
        "chart-5": "#b45309",
        sidebar: "#fff8e1",
        "sidebar-foreground": "#451a03",
        "sidebar-primary": "#d97706",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fef3c7",
        "sidebar-accent-foreground": "#92400e",
        "sidebar-border": "#fcd34d",
        "sidebar-ring": "#d97706",
        radius: "0.5rem",
      },
      dark: {
        background: "#1c1917",
        foreground: "#fef3c7",
        card: "#292524",
        "card-foreground": "#fef3c7",
        popover: "#292524",
        "popover-foreground": "#fef3c7",
        primary: "#f59e0b",
        "primary-foreground": "#1c1917",
        secondary: "#451a03",
        "secondary-foreground": "#fef3c7",
        muted: "#292524",
        "muted-foreground": "#d97706",
        accent: "#b45309",
        "accent-foreground": "#fef3c7",
        destructive: "#7f1d1d",
        "destructive-foreground": "#ffffff",
        border: "#44403c",
        input: "#292524",
        ring: "#f59e0b",
        "chart-1": "#f59e0b",
        "chart-2": "#d97706",
        "chart-3": "#b45309",
        "chart-4": "#92400e",
        "chart-5": "#78350f",
        sidebar: "#1c1917",
        "sidebar-foreground": "#fef3c7",
        "sidebar-primary": "#f59e0b",
        "sidebar-primary-foreground": "#1c1917",
        "sidebar-accent": "#451a03",
        "sidebar-accent-foreground": "#fef3c7",
        "sidebar-border": "#44403c",
        "sidebar-ring": "#f59e0b",
        radius: "0.5rem",
      },
    },
  },
  supabase: {
    label: "Supabase",
    createdAt: "2025-04-05",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#1c1c1c",
        card: "#ffffff",
        "card-foreground": "#1c1c1c",
        popover: "#ffffff",
        "popover-foreground": "#1c1c1c",
        primary: "#3ecf8e",
        "primary-foreground": "#ffffff",
        secondary: "#f0f0f0",
        "secondary-foreground": "#1c1c1c",
        muted: "#f9f9f9",
        "muted-foreground": "#686868",
        accent: "#3ecf8e",
        "accent-foreground": "#ffffff",
        destructive: "#fa4b4b",
        "destructive-foreground": "#ffffff",
        border: "#e1e1e1",
        input: "#f0f0f0",
        ring: "#3ecf8e",
        "chart-1": "#3ecf8e",
        "chart-2": "#24b47e",
        "chart-3": "#1c1c1c",
        "chart-4": "#686868",
        "chart-5": "#e1e1e1",
        sidebar: "#f9f9f9",
        "sidebar-foreground": "#1c1c1c",
        "sidebar-primary": "#3ecf8e",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f0f0f0",
        "sidebar-accent-foreground": "#1c1c1c",
        "sidebar-border": "#e1e1e1",
        "sidebar-ring": "#3ecf8e",
        radius: "0.375rem",
      },
      dark: {
        background: "#1c1c1c",
        foreground: "#ededed",
        card: "#171717",
        "card-foreground": "#ffffff",
        popover: "#1c1c1c",
        "popover-foreground": "#ededed",
        primary: "#3ecf8e",
        "primary-foreground": "#1c1c1c",
        secondary: "#282828",
        "secondary-foreground": "#ededed",
        muted: "#242424",
        "muted-foreground": "#909090",
        accent: "#3ecf8e",
        "accent-foreground": "#1c1c1c",
        destructive: "#fa4b4b",
        "destructive-foreground": "#ffffff",
        border: "#2e2e2e",
        input: "#282828",
        ring: "#3ecf8e",
        "chart-1": "#3ecf8e",
        "chart-2": "#24b47e",
        "chart-3": "#ededed",
        "chart-4": "#909090",
        "chart-5": "#2e2e2e",
        sidebar: "#171717",
        "sidebar-foreground": "#ededed",
        "sidebar-primary": "#3ecf8e",
        "sidebar-primary-foreground": "#1c1c1c",
        "sidebar-accent": "#282828",
        "sidebar-accent-foreground": "#ededed",
        "sidebar-border": "#2e2e2e",
        "sidebar-ring": "#3ecf8e",
        radius: "0.375rem",
      },
    },
  },

  "neo-brutalism": {
    label: "Neo Brutalism",
    createdAt: "2025-04-04",
    styles: {
      light: {
        background: "#fdfdfd",
        foreground: "#000000",
        card: "#f3f3f3",
        "card-foreground": "#000000",
        popover: "#ffffff",
        "popover-foreground": "#000000",
        primary: "#ffde03",
        "primary-foreground": "#000000",
        secondary: "#000000",
        "secondary-foreground": "#ffffff",
        muted: "#e0e0e0",
        "muted-foreground": "#000000",
        accent: "#00ff00",
        "accent-foreground": "#000000",
        destructive: "#ff0000",
        "destructive-foreground": "#ffffff",
        border: "#000000",
        input: "#ffffff",
        ring: "#000000",
        "chart-1": "#ffde03",
        "chart-2": "#00ff00",
        "chart-3": "#0000ff",
        "chart-4": "#ff00ff",
        "chart-5": "#ff0000",
        sidebar: "#f3f3f3",
        "sidebar-foreground": "#000000",
        "sidebar-primary": "#ffde03",
        "sidebar-primary-foreground": "#000000",
        "sidebar-accent": "#00ff00",
        "sidebar-accent-foreground": "#000000",
        "sidebar-border": "#000000",
        "sidebar-ring": "#000000",
        radius: "0rem",
        "shadow-color": "#000000",
        "shadow-opacity": "1.0",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "4px",
        "shadow-offset-y": "4px",
      },
      dark: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#121212",
        "card-foreground": "#ffffff",
        popover: "#000000",
        "popover-foreground": "#ffffff",
        primary: "#ffde03",
        "primary-foreground": "#000000",
        secondary: "#ffffff",
        "secondary-foreground": "#000000",
        muted: "#262626",
        "muted-foreground": "#ffffff",
        accent: "#00ff00",
        "accent-foreground": "#000000",
        destructive: "#ff0000",
        "destructive-foreground": "#ffffff",
        border: "#ffffff",
        input: "#000000",
        ring: "#ffffff",
        "chart-1": "#ffde03",
        "chart-2": "#00ff00",
        "chart-3": "#0000ff",
        "chart-4": "#ff00ff",
        "chart-5": "#ff0000",
        sidebar: "#121212",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#ffde03",
        "sidebar-primary-foreground": "#000000",
        "sidebar-accent": "#00ff00",
        "sidebar-accent-foreground": "#000000",
        "sidebar-border": "#ffffff",
        "sidebar-ring": "#ffffff",
        radius: "0rem",
        "shadow-color": "#ffffff",
        "shadow-opacity": "1.0",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "4px",
        "shadow-offset-y": "4px",
      },
    },
  },

  "solar-dusk": {
    label: "Solar Dusk",
    createdAt: "2025-04-03",
    styles: {
      light: {
        background: "#fdf6e3",
        foreground: "#657b83",
        card: "#eee8d5",
        "card-foreground": "#657b83",
        popover: "#fdf6e3",
        "popover-foreground": "#657b83",
        primary: "#b58900",
        "primary-foreground": "#ffffff",
        secondary: "#93a1a1",
        "secondary-foreground": "#ffffff",
        muted: "#eee8d5",
        "muted-foreground": "#839496",
        accent: "#268bd2",
        "accent-foreground": "#ffffff",
        destructive: "#dc322f",
        "destructive-foreground": "#ffffff",
        border: "#d5ccba",
        input: "#eee8d5",
        ring: "#b58900",
        "chart-1": "#b58900",
        "chart-2": "#cb4b16",
        "chart-3": "#dc322f",
        "chart-4": "#d33682",
        "chart-5": "#6c71c4",
        sidebar: "#eee8d5",
        "sidebar-foreground": "#657b83",
        "sidebar-primary": "#b58900",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fdf6e3",
        "sidebar-accent-foreground": "#657b83",
        "sidebar-border": "#d5ccba",
        "sidebar-ring": "#b58900",
        radius: "0.375rem",
      },
      dark: {
        background: "#002b36",
        foreground: "#839496",
        card: "#073642",
        "card-foreground": "#839496",
        popover: "#002b36",
        "popover-foreground": "#839496",
        primary: "#268bd2",
        "primary-foreground": "#ffffff",
        secondary: "#586e75",
        "secondary-foreground": "#ffffff",
        muted: "#073642",
        "muted-foreground": "#657b83",
        accent: "#859900",
        "accent-foreground": "#ffffff",
        destructive: "#dc322f",
        "destructive-foreground": "#ffffff",
        border: "#0b4e5f",
        input: "#073642",
        ring: "#268bd2",
        "chart-1": "#268bd2",
        "chart-2": "#2aa198",
        "chart-3": "#859900",
        "chart-4": "#b58900",
        "chart-5": "#cb4b16",
        sidebar: "#073642",
        "sidebar-foreground": "#839496",
        "sidebar-primary": "#268bd2",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#002b36",
        "sidebar-accent-foreground": "#839496",
        "sidebar-border": "#0b4e5f",
        "sidebar-ring": "#268bd2",
        radius: "0.375rem",
      },
    },
  },

  claymorphism: {
    label: "Claymorphism",
    createdAt: "2025-04-02",
    styles: {
      light: {
        background: "#f0f4f8",
        foreground: "#2d3748",
        card: "#ffffff",
        "card-foreground": "#2d3748",
        popover: "#ffffff",
        "popover-foreground": "#2d3748",
        primary: "#667eea",
        "primary-foreground": "#ffffff",
        secondary: "#edf2f7",
        "secondary-foreground": "#2d3748",
        muted: "#edf2f7",
        "muted-foreground": "#718096",
        accent: "#76e4f7",
        "accent-foreground": "#2d3748",
        destructive: "#f56565",
        "destructive-foreground": "#ffffff",
        border: "#e2e8f0",
        input: "#edf2f7",
        ring: "#667eea",
        "chart-1": "#667eea",
        "chart-2": "#76e4f7",
        "chart-3": "#9f7aea",
        "chart-4": "#ed64a6",
        "chart-5": "#f56565",
        radius: "2rem",
        "shadow-color": "hsl(210 25% 60% / 0.3)",
        "shadow-opacity": "0.4",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "8px",
        "shadow-offset-y": "8px",
      },
      dark: {
        background: "#1a202c",
        foreground: "#edf2f7",
        card: "#2d3748",
        "card-foreground": "#edf2f7",
        popover: "#2d3748",
        "popover-foreground": "#edf2f7",
        primary: "#7f9cf5",
        "primary-foreground": "#1a202c",
        secondary: "#4a5568",
        "secondary-foreground": "#edf2f7",
        muted: "#2d3748",
        "muted-foreground": "#a0aec0",
        accent: "#0bc5ea",
        "accent-foreground": "#1a202c",
        destructive: "#fc8181",
        "destructive-foreground": "#1a202c",
        border: "#4a5568",
        input: "#2d3748",
        ring: "#7f9cf5",
        "chart-1": "#7f9cf5",
        "chart-2": "#0bc5ea",
        "chart-3": "#b794f4",
        "chart-4": "#f66d9b",
        "chart-5": "#fc8181",
        radius: "2rem",
        "shadow-color": "hsl(220 30% 10% / 0.5)",
        "shadow-opacity": "0.6",
        "shadow-blur": "15px",
        "shadow-spread": "0px",
        "shadow-offset-x": "10px",
        "shadow-offset-y": "10px",
      },
    },
  },

  cyberpunk: {
    label: "Cyberpunk",
    createdAt: "2025-04-01",
    styles: {
      light: {
        background: "#fff017",
        foreground: "#000000",
        card: "#00ffcc",
        "card-foreground": "#000000",
        popover: "#ff00ff",
        "popover-foreground": "#ffffff",
        primary: "#000000",
        "primary-foreground": "#fff017",
        secondary: "#00ffcc",
        "secondary-foreground": "#000000",
        muted: "#000000",
        "muted-foreground": "#fff017",
        accent: "#ff00ff",
        "accent-foreground": "#ffffff",
        destructive: "#ff0033",
        "destructive-foreground": "#ffffff",
        border: "#000000",
        input: "#ffffff",
        ring: "#ff00ff",
        "chart-1": "#000000",
        "chart-2": "#00ffcc",
        "chart-3": "#ff00ff",
        "chart-4": "#fff017",
        "chart-5": "#ff0033",
        radius: "0rem",
        "shadow-color": "#000000",
        "shadow-opacity": "1.0",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "6px",
        "shadow-offset-y": "6px",
      },
      dark: {
        background: "#000000",
        foreground: "#fff017",
        card: "#1a1a1a",
        "card-foreground": "#00ffcc",
        popover: "#1a1a1a",
        "popover-foreground": "#ff00ff",
        primary: "#fff017",
        "primary-foreground": "#000000",
        secondary: "#00ffcc",
        "secondary-foreground": "#000000",
        muted: "#1a1a1a",
        "muted-foreground": "#fff017",
        accent: "#ff00ff",
        "accent-foreground": "#000000",
        destructive: "#ff0033",
        "destructive-foreground": "#ffffff",
        border: "#fff017",
        input: "#000000",
        ring: "#00ffcc",
        "chart-1": "#fff017",
        "chart-2": "#00ffcc",
        "chart-3": "#ff00ff",
        "chart-4": "#ffffff",
        "chart-5": "#ff0033",
        radius: "0rem",
        "shadow-color": "#fff017",
        "shadow-opacity": "1.0",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "6px",
        "shadow-offset-y": "6px",
      },
    },
  },

  "pastel-dreams": {
    label: "Pastel Dreams",
    createdAt: "2025-03-31",
    styles: {
      light: {
        background: "#fff5f7",
        foreground: "#4a4a4a",
        card: "#fff9eb",
        "card-foreground": "#4a4a4a",
        popover: "#ffffff",
        "popover-foreground": "#4a4a4a",
        primary: "#ffb7b2",
        "primary-foreground": "#ffffff",
        secondary: "#b2e2f2",
        "secondary-foreground": "#4a4a4a",
        muted: "#e2f2b2",
        "muted-foreground": "#4a4a4a",
        accent: "#f2b2e2",
        "accent-foreground": "#ffffff",
        destructive: "#ff9aa2",
        "destructive-foreground": "#ffffff",
        border: "#f3e5f5",
        input: "#ffffff",
        ring: "#ffb7b2",
        "chart-1": "#ffb7b2",
        "chart-2": "#b2e2f2",
        "chart-3": "#e2f2b2",
        "chart-4": "#f2b2e2",
        "chart-5": "#ff9aa2",
        radius: "1.25rem",
      },
      dark: {
        background: "#2d2a2a",
        foreground: "#fcefed",
        card: "#3d3838",
        "card-foreground": "#fcefed",
        popover: "#3d3838",
        "popover-foreground": "#fcefed",
        primary: "#ff8a80",
        "primary-foreground": "#2d2a2a",
        secondary: "#80deea",
        "secondary-foreground": "#2d2a2a",
        muted: "#3d3838",
        "muted-foreground": "#ff8a80",
        accent: "#ea80fc",
        "accent-foreground": "#2d2a2a",
        destructive: "#ff5252",
        "destructive-foreground": "#ffffff",
        border: "#4a4444",
        input: "#3d3838",
        ring: "#ff8a80",
        "chart-1": "#ff8a80",
        "chart-2": "#80deea",
        "chart-3": "#c5e1a5",
        "chart-4": "#f48fb1",
        "chart-5": "#ff5252",
        radius: "1.25rem",
      },
    },
  },

  "clean-slate": {
    label: "Clean Slate",
    createdAt: "2025-03-30",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#111827",
        card: "#ffffff",
        "card-foreground": "#111827",
        popover: "#ffffff",
        "popover-foreground": "#111827",
        primary: "#111827",
        "primary-foreground": "#ffffff",
        secondary: "#f3f4f6",
        "secondary-foreground": "#111827",
        muted: "#f9fafb",
        "muted-foreground": "#6b7280",
        accent: "#f3f4f6",
        "accent-foreground": "#111827",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#e5e7eb",
        input: "#f3f4f6",
        ring: "#111827",
        "chart-1": "#111827",
        "chart-2": "#4b5563",
        "chart-3": "#9ca3af",
        "chart-4": "#d1d5db",
        "chart-5": "#f3f4f6",
        radius: "0.25rem",
      },
      dark: {
        background: "#111827",
        foreground: "#f9fafb",
        card: "#1f2937",
        "card-foreground": "#f9fafb",
        popover: "#1f2937",
        "popover-foreground": "#f9fafb",
        primary: "#f9fafb",
        "primary-foreground": "#111827",
        secondary: "#374151",
        "secondary-foreground": "#f9fafb",
        muted: "#1f2937",
        "muted-foreground": "#9ca3af",
        accent: "#374151",
        "accent-foreground": "#f9fafb",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#374151",
        input: "#1f2937",
        ring: "#f9fafb",
        "chart-1": "#f9fafb",
        "chart-2": "#d1d5db",
        "chart-3": "#9ca3af",
        "chart-4": "#4b5563",
        "chart-5": "#374151",
        radius: "0.25rem",
      },
    },
  },
  caffeine: {
    label: "Caffeine",
    createdAt: "2025-03-29",
    styles: {
      light: {
        background: "#fdf8f5",
        foreground: "#3e2723",
        card: "#ffffff",
        "card-foreground": "#3e2723",
        popover: "#ffffff",
        "popover-foreground": "#3e2723",
        primary: "#6d4c41",
        "primary-foreground": "#ffffff",
        secondary: "#d7ccc8",
        "secondary-foreground": "#3e2723",
        muted: "#efebe9",
        "muted-foreground": "#8d6e63",
        accent: "#a1887f",
        "accent-foreground": "#ffffff",
        destructive: "#d32f2f",
        "destructive-foreground": "#ffffff",
        border: "#d7ccc8",
        input: "#efebe9",
        ring: "#6d4c41",
        "chart-1": "#6d4c41",
        "chart-2": "#8d6e63",
        "chart-3": "#a1887f",
        "chart-4": "#bcaaa4",
        "chart-5": "#d7ccc8",
        radius: "0.5rem",
      },
      dark: {
        background: "#1b1411",
        foreground: "#efebe9",
        card: "#2d221e",
        "card-foreground": "#efebe9",
        popover: "#2d221e",
        "popover-foreground": "#efebe9",
        primary: "#a1887f",
        "primary-foreground": "#1b1411",
        secondary: "#4e342e",
        "secondary-foreground": "#efebe9",
        muted: "#2d221e",
        "muted-foreground": "#bcaaa4",
        accent: "#6d4c41",
        "accent-foreground": "#ffffff",
        destructive: "#ef5350",
        "destructive-foreground": "#ffffff",
        border: "#4e342e",
        input: "#2d221e",
        ring: "#a1887f",
        "chart-1": "#a1887f",
        "chart-2": "#8d6e63",
        "chart-3": "#6d4c41",
        "chart-4": "#4e342e",
        "chart-5": "#3a2a24",
        radius: "0.5rem",
      },
    },
  },

  "ocean-breeze": {
    label: "Ocean Breeze",
    createdAt: "2025-03-28",
    styles: {
      light: {
        background: "#f0f9ff",
        foreground: "#0c4a6e",
        card: "#ffffff",
        "card-foreground": "#0c4a6e",
        popover: "#ffffff",
        "popover-foreground": "#0c4a6e",
        primary: "#0284c7",
        "primary-foreground": "#ffffff",
        secondary: "#e0f2fe",
        "secondary-foreground": "#0369a1",
        muted: "#f0f9ff",
        "muted-foreground": "#075985",
        accent: "#7dd3fc",
        "accent-foreground": "#0c4a6e",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#bae6fd",
        input: "#e0f2fe",
        ring: "#0284c7",
        "chart-1": "#0284c7",
        "chart-2": "#0ea5e9",
        "chart-3": "#38bdf8",
        "chart-4": "#7dd3fc",
        "chart-5": "#bae6fd",
        radius: "0.5rem",
      },
      dark: {
        background: "#082f49",
        foreground: "#f0f9ff",
        card: "#0c4a6e",
        "card-foreground": "#f0f9ff",
        popover: "#0c4a6e",
        "popover-foreground": "#f0f9ff",
        primary: "#38bdf8",
        "primary-foreground": "#082f49",
        secondary: "#075985",
        "secondary-foreground": "#f0f9ff",
        muted: "#0c4a6e",
        "muted-foreground": "#7dd3fc",
        accent: "#0ea5e9",
        "accent-foreground": "#ffffff",
        destructive: "#fb7185",
        "destructive-foreground": "#ffffff",
        border: "#075985",
        input: "#0c4a6e",
        ring: "#38bdf8",
        "chart-1": "#38bdf8",
        "chart-2": "#0ea5e9",
        "chart-3": "#0284c7",
        "chart-4": "#0369a1",
        "chart-5": "#075985",
        radius: "0.5rem",
      },
    },
  },

  "retro-arcade": {
    label: "Retro Arcade",
    createdAt: "2025-03-27",
    styles: {
      light: {
        background: "#f8f9fa",
        foreground: "#212529",
        card: "#ffffff",
        "card-foreground": "#212529",
        popover: "#ffffff",
        "popover-foreground": "#212529",
        primary: "#ff0055",
        "primary-foreground": "#ffffff",
        secondary: "#00d4ff",
        "secondary-foreground": "#212529",
        muted: "#e9ecef",
        "muted-foreground": "#6c757d",
        accent: "#39ff14",
        "accent-foreground": "#212529",
        destructive: "#ff3131",
        "destructive-foreground": "#ffffff",
        border: "#dee2e6",
        input: "#f1f3f5",
        ring: "#ff0055",
        "chart-1": "#ff0055",
        "chart-2": "#00d4ff",
        "chart-3": "#39ff14",
        "chart-4": "#ffcc00",
        "chart-5": "#ff00ff",
        radius: "0rem",
      },
      dark: {
        background: "#121212",
        foreground: "#f8f9fa",
        card: "#1e1e1e",
        "card-foreground": "#f8f9fa",
        popover: "#1e1e1e",
        "popover-foreground": "#f8f9fa",
        primary: "#ff0055",
        "primary-foreground": "#ffffff",
        secondary: "#00d4ff",
        "secondary-foreground": "#ffffff",
        muted: "#212529",
        "muted-foreground": "#adb5bd",
        accent: "#39ff14",
        "accent-foreground": "#ffffff",
        destructive: "#ff3131",
        "destructive-foreground": "#ffffff",
        border: "#343a40",
        input: "#212529",
        ring: "#ff0055",
        "chart-1": "#ff0055",
        "chart-2": "#00d4ff",
        "chart-3": "#39ff14",
        "chart-4": "#ffcc00",
        "chart-5": "#ff00ff",
        radius: "0rem",
      },
    },
  },

  "midnight-bloom": {
    label: "Midnight Bloom",
    createdAt: "2025-03-26",
    styles: {
      light: {
        background: "#faf5ff",
        foreground: "#2d1b4e",
        card: "#ffffff",
        "card-foreground": "#2d1b4e",
        popover: "#ffffff",
        "popover-foreground": "#2d1b4e",
        primary: "#7c3aed",
        "primary-foreground": "#ffffff",
        secondary: "#f3e8ff",
        "secondary-foreground": "#6d28d9",
        muted: "#f5f3ff",
        "muted-foreground": "#7c3aed",
        accent: "#d8b4fe",
        "accent-foreground": "#4c1d95",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#e9d5ff",
        input: "#f3e8ff",
        ring: "#7c3aed",
        "chart-1": "#7c3aed",
        "chart-2": "#a855f7",
        "chart-3": "#d946ef",
        "chart-4": "#ec4899",
        "chart-5": "#f43f5e",
        radius: "0.75rem",
      },
      dark: {
        background: "#0f0717",
        foreground: "#f5f3ff",
        card: "#1a0b2e",
        "card-foreground": "#f5f3ff",
        popover: "#1a0b2e",
        "popover-foreground": "#f5f3ff",
        primary: "#a78bfa",
        "primary-foreground": "#0f0717",
        secondary: "#2e1065",
        "secondary-foreground": "#f5f3ff",
        muted: "#1a0b2e",
        "muted-foreground": "#c4b5fd",
        accent: "#4c1d95",
        "accent-foreground": "#ffffff",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#2e1065",
        input: "#1a0b2e",
        ring: "#a78bfa",
        "chart-1": "#a78bfa",
        "chart-2": "#c084fc",
        "chart-3": "#e879f9",
        "chart-4": "#f472b6",
        "chart-5": "#fb7185",
        radius: "0.75rem",
      },
    },
  },

  candyland: {
    label: "Candyland",
    createdAt: "2025-03-25",
    styles: {
      light: {
        background: "#fff0f6",
        foreground: "#a61e4d",
        card: "#ffffff",
        "card-foreground": "#a61e4d",
        popover: "#ffffff",
        "popover-foreground": "#a61e4d",
        primary: "#f06595",
        "primary-foreground": "#ffffff",
        secondary: "#ffdeeb",
        "secondary-foreground": "#c2255c",
        muted: "#fff0f6",
        "muted-foreground": "#d6336c",
        accent: "#fcc419",
        "accent-foreground": "#ffffff",
        destructive: "#fa5252",
        "destructive-foreground": "#ffffff",
        border: "#ffdeeb",
        input: "#fff5f5",
        ring: "#f06595",
        "chart-1": "#f06595",
        "chart-2": "#f783ac",
        "chart-3": "#fcc419",
        "chart-4": "#fa5252",
        "chart-5": "#be4bdb",
        radius: "1.5rem",
      },
      dark: {
        background: "#2b1111",
        foreground: "#fff0f6",
        card: "#3d1919",
        "card-foreground": "#fff0f6",
        popover: "#3d1919",
        "popover-foreground": "#fff0f6",
        primary: "#f783ac",
        "primary-foreground": "#2b1111",
        secondary: "#a61e4d",
        "secondary-foreground": "#ffffff",
        muted: "#3d1919",
        "muted-foreground": "#f06595",
        accent: "#fcc419",
        "accent-foreground": "#2b1111",
        destructive: "#ff8787",
        "destructive-foreground": "#2b1111",
        border: "#a61e4d",
        input: "#3d1919",
        ring: "#f783ac",
        "chart-1": "#f783ac",
        "chart-2": "#f06595",
        "chart-3": "#fab005",
        "chart-4": "#ff6b6b",
        "chart-5": "#da77f2",
        radius: "1.5rem",
      },
    },
  },

  "northern-lights": {
    label: "Northern Lights",
    createdAt: "2025-03-24",
    styles: {
      light: {
        background: "#f0faf5",
        foreground: "#0a2e1f",
        card: "#ffffff",
        "card-foreground": "#0a2e1f",
        popover: "#ffffff",
        "popover-foreground": "#0a2e1f",
        primary: "#10b981",
        "primary-foreground": "#ffffff",
        secondary: "#d1fae5",
        "secondary-foreground": "#065f46",
        muted: "#f0fdf4",
        "muted-foreground": "#10b981",
        accent: "#34d399",
        "accent-foreground": "#064e3b",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#a7f3d0",
        input: "#d1fae5",
        ring: "#10b981",
        "chart-1": "#10b981",
        "chart-2": "#34d399",
        "chart-3": "#6ee7b7",
        "chart-4": "#6366f1",
        "chart-5": "#8b5cf6",
        radius: "0.5rem",
      },
      dark: {
        background: "#06170f",
        foreground: "#d1fae5",
        card: "#0d2e1f",
        "card-foreground": "#d1fae5",
        popover: "#0d2e1f",
        "popover-foreground": "#d1fae5",
        primary: "#34d399",
        "primary-foreground": "#06170f",
        secondary: "#064e3b",
        "secondary-foreground": "#d1fae5",
        muted: "#0d2e1f",
        "muted-foreground": "#10b981",
        accent: "#10b981",
        "accent-foreground": "#ffffff",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#064e3b",
        input: "#0d2e1f",
        ring: "#34d399",
        "chart-1": "#34d399",
        "chart-2": "#10b981",
        "chart-3": "#059669",
        "chart-4": "#4338ca",
        "chart-5": "#6d28d9",
        radius: "0.5rem",
      },
    },
  },
  "vintage-paper": {
    label: "Vintage Paper",
    createdAt: "2025-03-23",
    styles: {
      light: {
        background: "#f4f1ea",
        foreground: "#4b4843",
        card: "#f9f7f2",
        "card-foreground": "#4b4843",
        popover: "#ffffff",
        "popover-foreground": "#4b4843",
        primary: "#8b7e66",
        "primary-foreground": "#ffffff",
        secondary: "#e8e4d9",
        "secondary-foreground": "#4b4843",
        muted: "#f4f1ea",
        "muted-foreground": "#8b7e66",
        accent: "#d4c5a9",
        "accent-foreground": "#4b4843",
        destructive: "#a35b5b",
        "destructive-foreground": "#ffffff",
        border: "#dcd7cd",
        input: "#e8e4d9",
        ring: "#8b7e66",
        "chart-1": "#8b7e66",
        "chart-2": "#a35b5b",
        "chart-3": "#6b8a7a",
        "chart-4": "#d4c5a9",
        "chart-5": "#4b4843",
        radius: "0rem",
      },
      dark: {
        background: "#2c2a27",
        foreground: "#e8e4d9",
        card: "#3a3834",
        "card-foreground": "#e8e4d9",
        popover: "#3a3834",
        "popover-foreground": "#e8e4d9",
        primary: "#d4c5a9",
        "primary-foreground": "#2c2a27",
        secondary: "#4b4843",
        "secondary-foreground": "#e8e4d9",
        muted: "#3a3834",
        "muted-foreground": "#b5ad9a",
        accent: "#8b7e66",
        "accent-foreground": "#ffffff",
        destructive: "#bf6161",
        "destructive-foreground": "#ffffff",
        border: "#4b4843",
        input: "#3a3834",
        ring: "#d4c5a9",
        "chart-1": "#d4c5a9",
        "chart-2": "#8b7e66",
        "chart-3": "#6b8a7a",
        "chart-4": "#a35b5b",
        "chart-5": "#e8e4d9",
        radius: "0rem",
      },
    },
  },

  "sunset-horizon": {
    label: "Sunset Horizon",
    createdAt: "2025-03-22",
    styles: {
      light: {
        background: "#fff9f0",
        foreground: "#432818",
        card: "#ffffff",
        "card-foreground": "#432818",
        popover: "#ffffff",
        "popover-foreground": "#432818",
        primary: "#f48c06",
        "primary-foreground": "#ffffff",
        secondary: "#ffca3a",
        "secondary-foreground": "#432818",
        muted: "#fff0db",
        "muted-foreground": "#9d4203",
        accent: "#ff6d00",
        "accent-foreground": "#ffffff",
        destructive: "#d00000",
        "destructive-foreground": "#ffffff",
        border: "#ffca3a",
        input: "#fff0db",
        ring: "#f48c06",
        "chart-1": "#f48c06",
        "chart-2": "#ffca3a",
        "chart-3": "#ff6d00",
        "chart-4": "#ff9e00",
        "chart-5": "#ff5400",
        radius: "0.5rem",
      },
      dark: {
        background: "#1a0f00",
        foreground: "#ffca3a",
        card: "#331a00",
        "card-foreground": "#ffca3a",
        popover: "#331a00",
        "popover-foreground": "#ffca3a",
        primary: "#ff9e00",
        "primary-foreground": "#1a0f00",
        secondary: "#432818",
        "secondary-foreground": "#ffca3a",
        muted: "#331a00",
        "muted-foreground": "#f48c00",
        accent: "#ff6d00",
        "accent-foreground": "#ffffff",
        destructive: "#ff4d4d",
        "destructive-foreground": "#ffffff",
        border: "#432818",
        input: "#331a00",
        ring: "#ff9e00",
        "chart-1": "#ff9e00",
        "chart-2": "#f48c06",
        "chart-3": "#ff6d00",
        "chart-4": "#ff5400",
        "chart-5": "#d00000",
        radius: "0.5rem",
      },
    },
  },

  "starry-night": {
    label: "Starry Night",
    createdAt: "2025-03-21",
    styles: {
      light: {
        background: "#f0f4f8",
        foreground: "#1a365d",
        card: "#ffffff",
        "card-foreground": "#1a365d",
        popover: "#ffffff",
        "popover-foreground": "#1a365d",
        primary: "#2a4365",
        "primary-foreground": "#ffffff",
        secondary: "#e2e8f0",
        "secondary-foreground": "#1a365d",
        muted: "#f7fafc",
        "muted-foreground": "#4a5568",
        accent: "#ecc94b",
        "accent-foreground": "#1a365d",
        destructive: "#e53e3e",
        "destructive-foreground": "#ffffff",
        border: "#cbd5e0",
        input: "#edf2f7",
        ring: "#2a4365",
        "chart-1": "#2a4365",
        "chart-2": "#ecc94b",
        "chart-3": "#4299e1",
        "chart-4": "#667eea",
        "chart-5": "#9f7aea",
        radius: "0.375rem",
      },
      dark: {
        background: "#0a192f",
        foreground: "#ccd6f6",
        card: "#112240",
        "card-foreground": "#ccd6f6",
        popover: "#112240",
        "popover-foreground": "#ccd6f6",
        primary: "#64ffda",
        "primary-foreground": "#0a192f",
        secondary: "#233554",
        "secondary-foreground": "#ccd6f6",
        muted: "#112240",
        "muted-foreground": "#8892b0",
        accent: "#64ffda",
        "accent-foreground": "#0a192f",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#233554",
        input: "#112240",
        ring: "#64ffda",
        "chart-1": "#64ffda",
        "chart-2": "#8892b0",
        "chart-3": "#ccd6f6",
        "chart-4": "#112240",
        "chart-5": "#233554",
        radius: "0.375rem",
      },
    },
  },

  claude: {
    label: "Claude",
    createdAt: "2025-04-12",
    styles: {
      light: {
        background: "#fbfaf8",
        foreground: "#1d1d1b",
        card: "#f4f0e8",
        "card-foreground": "#1d1d1b",
        popover: "#f4f0e8",
        "popover-foreground": "#1d1d1b",
        primary: "#d97757",
        "primary-foreground": "#ffffff",
        secondary: "#e6e1d6",
        "secondary-foreground": "#4d4d4b",
        muted: "#f2efe9",
        "muted-foreground": "#8c8c88",
        accent: "#d97757",
        "accent-foreground": "#ffffff",
        destructive: "#cb4434",
        "destructive-foreground": "#ffffff",
        border: "#e5e2da",
        input: "#e5e2da",
        ring: "#d97757",
        "chart-1": "#d77757",
        "chart-2": "#1d1d1b",
        "chart-3": "#e2ddcf",
        "chart-4": "#8c8c88",
        "chart-5": "#f4f0e8",
        sidebar: "#f5f2eb",
        "sidebar-foreground": "#1d1d1b",
        "sidebar-primary": "#d97757",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e6e1d6",
        "sidebar-accent-foreground": "#1d1d1b",
        "sidebar-border": "#e5e2da",
        "sidebar-ring": "#d97757",
        radius: "0.45rem",
      },
      dark: {
        background: "#1d1d1b",
        foreground: "#f4f0e8",
        card: "#262624",
        "card-foreground": "#f4f0e8",
        popover: "#262624",
        "popover-foreground": "#f4f0e8",
        primary: "#d97757",
        "primary-foreground": "#ffffff",
        secondary: "#333331",
        "secondary-foreground": "#f4f0e8",
        muted: "#262624",
        "muted-foreground": "#8c8c88",
        accent: "#d97757",
        "accent-foreground": "#ffffff",
        destructive: "#cb4434",
        "destructive-foreground": "#ffffff",
        border: "#333331",
        input: "#333331",
        ring: "#d97757",
        "chart-1": "#d77757",
        "chart-2": "#f4f0e8",
        "chart-3": "#333331",
        "chart-4": "#8c8c88",
        "chart-5": "#262624",
        sidebar: "#171715",
        "sidebar-foreground": "#f4f0e8",
        "sidebar-primary": "#d97757",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#333331",
        "sidebar-accent-foreground": "#f4f0e8",
        "sidebar-border": "#333331",
        "sidebar-ring": "#d97757",
        radius: "0.45rem",
      },
    },
  },

  vercel: {
    label: "Vercel",
    createdAt: "2025-04-12",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "oklch(0.145 0 0)",
        card: "#ffffff",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "#ffffff",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "oklch(0.205 0 0)",
        "primary-foreground": "oklch(0.985 0 0)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.985 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "oklch(0.708 0 0)",
        "chart-1": "oklch(0.646 0.222 41.116)",
        "chart-2": "oklch(0.6 0.118 184.704)",
        "chart-3": "oklch(0.398 0.07 227.392)",
        "chart-4": "oklch(0.828 0.189 84.429)",
        "chart-5": "oklch(0.769 0.188 70.08)",
        radius: "0.5rem",
        sidebar: "oklch(0.985 0 0)",
        "sidebar-foreground": "oklch(0.145 0 0)",
        "sidebar-primary": "oklch(0.205 0 0)",
        "sidebar-primary-foreground": "oklch(0.985 0 0)",
        "sidebar-accent": "oklch(0.97 0 0)",
        "sidebar-accent-foreground": "oklch(0.205 0 0)",
        "sidebar-border": "oklch(0.922 0 0)",
        "sidebar-ring": "oklch(0.708 0 0)",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.205 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "oklch(0.985 0 0)",
        "primary-foreground": "oklch(0.205 0 0)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.269 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.396 0.141 25.723)",
        "destructive-foreground": "oklch(0.985 0 0)",
        border: "oklch(0.269 0 0)",
        input: "oklch(0.269 0 0)",
        ring: "oklch(0.439 0 0)",
        "chart-1": "oklch(0.488 0.243 264.376)",
        "chart-2": "oklch(0.696 0.17 162.48)",
        "chart-3": "oklch(0.769 0.188 70.08)",
        "chart-4": "oklch(0.627 0.265 303.9)",
        "chart-5": "oklch(0.645 0.246 16.439)",
        radius: "0.5rem",
        sidebar: "oklch(0.145 0 0)",
        "sidebar-foreground": "oklch(0.985 0 0)",
        "sidebar-primary": "oklch(0.205 0 0)",
        "sidebar-primary-foreground": "oklch(0.985 0 0)",
        "sidebar-accent": "oklch(0.269 0 0)",
        "sidebar-accent-foreground": "oklch(0.985 0 0)",
        "sidebar-border": "oklch(0.269 0 0)",
        "sidebar-ring": "oklch(0.439 0 0)",
      },
    },
  },

  darkmatter: {
    label: "Darkmatter",
    createdAt: "2025-05-18",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#111111",
        card: "#ffffff",
        "card-foreground": "#111111",
        popover: "#ffffff",
        "popover-foreground": "#111111",
        primary: "#111111",
        "primary-foreground": "#ffffff",
        secondary: "#f4f4f4",
        "secondary-foreground": "#111111",
        muted: "#f4f4f4",
        "muted-foreground": "#666666",
        accent: "#f4f4f4",
        "accent-foreground": "#111111",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#e5e5e5",
        input: "#e5e5e5",
        ring: "#111111",
        "chart-1": "#111111",
        "chart-2": "#666666",
        "chart-3": "#999999",
        "chart-4": "#cccccc",
        "chart-5": "#eeeeee",
        radius: "0rem",
      },
      dark: {
        background: "#060606",
        foreground: "#ffffff",
        card: "#0a0a0a",
        "card-foreground": "#ffffff",
        popover: "#0a0a0a",
        "popover-foreground": "#ffffff",
        primary: "#ffffff",
        "primary-foreground": "#060606",
        secondary: "#111111",
        "secondary-foreground": "#ffffff",
        muted: "#111111",
        "muted-foreground": "#888888",
        accent: "#111111",
        "accent-foreground": "#ffffff",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#1a1a1a",
        input: "#1a1a1a",
        ring: "#ffffff",
        "chart-1": "#ffffff",
        "chart-2": "#888888",
        "chart-3": "#444444",
        "chart-4": "#222222",
        "chart-5": "#111111",
        radius: "0rem",
      },
    },
  },

  mono: {
    label: "Mono",
    createdAt: "2025-04-18",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#ffffff",
        "card-foreground": "#000000",
        popover: "#ffffff",
        "popover-foreground": "#000000",
        primary: "#000000",
        "primary-foreground": "#ffffff",
        secondary: "#f0f0f0",
        "secondary-foreground": "#000000",
        muted: "#f0f0f0",
        "muted-foreground": "#666666",
        accent: "#f0f0f0",
        "accent-foreground": "#000000",
        destructive: "#000000",
        "destructive-foreground": "#ffffff",
        border: "#000000",
        input: "#000000",
        ring: "#000000",
        "chart-1": "#000000",
        "chart-2": "#333333",
        "chart-3": "#666666",
        "chart-4": "#999999",
        "chart-5": "#cccccc",
        radius: "0rem",
      },
      dark: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#000000",
        "card-foreground": "#ffffff",
        popover: "#000000",
        "popover-foreground": "#ffffff",
        primary: "#ffffff",
        "primary-foreground": "#000000",
        secondary: "#1a1a1a",
        "secondary-foreground": "#ffffff",
        muted: "#1a1a1a",
        "muted-foreground": "#aaaaaa",
        accent: "#1a1a1a",
        "accent-foreground": "#ffffff",
        destructive: "#ffffff",
        "destructive-foreground": "#000000",
        border: "#ffffff",
        input: "#ffffff",
        ring: "#ffffff",
        "chart-1": "#ffffff",
        "chart-2": "#cccccc",
        "chart-3": "#999999",
        "chart-4": "#666666",
        "chart-5": "#333333",
        radius: "0rem",
      },
    },
  },

  "soft-pop": {
    label: "Soft Pop",
    createdAt: "2025-03-18",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#2d3748",
        card: "#ffffff",
        "card-foreground": "#2d3748",
        popover: "#ffffff",
        "popover-foreground": "#2d3748",
        primary: "#ff6b6b",
        "primary-foreground": "#ffffff",
        secondary: "#f7fafc",
        "secondary-foreground": "#2d3748",
        muted: "#edf2f7",
        "muted-foreground": "#718096",
        accent: "#ffd93d",
        "accent-foreground": "#2d3748",
        destructive: "#ff6b6b",
        "destructive-foreground": "#ffffff",
        border: "#e2e8f0",
        input: "#e2e8f0",
        ring: "#ff6b6b",
        "chart-1": "#ff6b6b",
        "chart-2": "#4ecdc4",
        "chart-3": "#ffd93d",
        "chart-4": "#6c5ce7",
        "chart-5": "#a29bfe",
        radius: "1rem",
        "shadow-color": "hsl(0 0% 0% / 0.1)",
        "shadow-opacity": "0.1",
        "shadow-blur": "10px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
      },
      dark: {
        background: "#1a202c",
        foreground: "#f7fafc",
        card: "#2d3748",
        "card-foreground": "#f7fafc",
        popover: "#2d3748",
        "popover-foreground": "#f7fafc",
        primary: "#ff6b6b",
        "primary-foreground": "#ffffff",
        secondary: "#4a5568",
        "secondary-foreground": "#f7fafc",
        muted: "#2d3748",
        "muted-foreground": "#a0aec0",
        accent: "#ffd93d",
        "accent-foreground": "#1a202c",
        destructive: "#ff6b6b",
        "destructive-foreground": "#ffffff",
        border: "#4a5568",
        input: "#4a5568",
        ring: "#ff6b6b",
        "chart-1": "#ff6b6b",
        "chart-2": "#4ecdc4",
        "chart-3": "#ffd93d",
        "chart-4": "#6c5ce7",
        "chart-5": "#a29bfe",
        radius: "1rem",
      },
    },
  },

  "sage-garden": {
    label: "Sage Garden",
    createdAt: "2025-03-12",
    styles: {
      light: {
        background: "#f0f4f1",
        foreground: "#2d3a2d",
        card: "#ffffff",
        "card-foreground": "#2d3a2d",
        popover: "#ffffff",
        "popover-foreground": "#2d3a2d",
        primary: "#6b8e6b",
        "primary-foreground": "#ffffff",
        secondary: "#dce4dc",
        "secondary-foreground": "#2d3a2d",
        muted: "#e8ede8",
        "muted-foreground": "#5a725a",
        accent: "#a3bfa3",
        "accent-foreground": "#2d3a2d",
        destructive: "#9e5a5a",
        "destructive-foreground": "#ffffff",
        border: "#ced6ce",
        input: "#dce4dc",
        ring: "#6b8e6b",
        "chart-1": "#6b8e6b",
        "chart-2": "#8e6b6b",
        "chart-3": "#6b6b8e",
        "chart-4": "#8e8e6b",
        "chart-5": "#6b8e8e",
        radius: "0.5rem",
      },
      dark: {
        background: "#1a201a",
        foreground: "#e8ede8",
        card: "#212a21",
        "card-foreground": "#e8ede8",
        popover: "#212a21",
        "popover-foreground": "#e8ede8",
        primary: "#8eb68e",
        "primary-foreground": "#1a201a",
        secondary: "#2d3a2d",
        "secondary-foreground": "#e8ede8",
        muted: "#212a21",
        "muted-foreground": "#a3bfa3",
        accent: "#5a725a",
        "accent-foreground": "#ffffff",
        destructive: "#bf6b6b",
        "destructive-foreground": "#ffffff",
        border: "#2d3a2d",
        input: "#212a21",
        ring: "#8eb68e",
        "chart-1": "#8eb68e",
        "chart-2": "#b68e8e",
        "chart-3": "#8e8eb6",
        "chart-4": "#b6b68e",
        "chart-5": "#8eb6b6",
        radius: "0.5rem",
      },
    },
  },
};

// Helper function to get all preset names
export function getAllPresetNames(): string[] {
  return ["default", ...Object.keys(defaultPresets)];
}

// Helper function to get a preset by name
export function getPreset(name: string): ThemePreset | null {
  if (name === "default") {
    return null; // Default theme is handled separately
  }
  return defaultPresets[name] || null;
}
